fragment ActiveOrder on Order {
  __typename
  id
  code
  couponCodes
  state
  currencyCode
  totalQuantity
  subTotalWithTax
  shippingWithTax
  totalWithTax
  discounts {
    description
    amountWithTax
  }
  lines {
    id
    unitPriceWithTax
    quantity
    linePriceWithTax
    productVariant {
      id
      sku
      product {
        name
        description
        languageCode
        translations {
          id
          slug
          name
          description
          languageCode
        }
        optionGroups {
          id
          code
          translations {
            languageCode
            name
          }
          options {
            id
            code
            translations {
              languageCode
              name
            }
          }
        }
      }
    }
    featuredAsset {
      id
      preview
    }
  }
  shippingLines {
    shippingMethod {
      description
    }
    priceWithTax
  }
}
