query getTopLevelCollections {
  collections(options: { topLevelOnly: true }) {
    items {
      languageCode
      name
      slug
      translations {
        languageCode
        name
        slug
      }
    }
  }
}
