query getProducts($skip: Int, $take: Int) {
  products(options: { skip: $skip, take: $take }) {
    totalItems
    items {
      id
      name
      slug
      featuredAsset {
        id
        source
        preview
      }
      assets {
        id
        source
        preview
      }
    }
  }
}

query getProduct($id: ID, $slug: String) {
  product(id: $id, slug: $slug) {
    id
    name
    slug
    featuredAsset {
      id
      source
      preview
    }
    assets {
      id
      source
      preview
    }
  }
}
