query GetProducts($skip: Int, $take: Int, $filter: ProductFilterParameter) {
  products(options: { skip: $skip, take: $take, filter: $filter }) {
    totalItems
    items {
      id
      name
      slug
      description
      featuredAsset {
        id
        source
        preview
      }
      assets {
        id
        source
        preview
      }
      translations {
        id
        slug
        name
        description
        languageCode
      }
    }
  }
}

query GetProduct($id: ID, $slug: String) {
  product(id: $id, slug: $slug) {
    id
    name
    slug
    description
    featuredAsset {
      id
      source
      preview
    }
    assets {
      id
      source
      preview
    }
    translations {
      id
      slug
      name
      description
      languageCode
    }
  }
}
